### PR TITLE
Add information about USB joysticks and virtual thumbsticks

### PR DESCRIPTION
**Pull request by hamishwillee**
Hi @DonLakeFlyer , I added this as somewhere to link to from PX4 simulation docs. There are a number of open questions:

- Does virtual thumbstick work for both Ardupilot and PX4?
- Does USB Joystick work for ArduPilot too?
  - If so, what do you need to do to enable it for Ardupilot (e.g. for PX4 you have to set a parameter)
- Can you enable both virtual thumbsticks and a USB joystick?
- I have listed a few joysticks that I either tested (Taranis, PS4) or were documented in old qgroundcontrol. Do we know of any more - if so which, and any limitations known?
- What "protocol" must a joystick follow to work. ie are joysticks sufficiently common in terms of USB protocol that we can say "any usb two-stick joystick has a good chance of working"?
- The PX4 param has another option "Virtual RC by Joystick" - what does this do?

Is there anything else you think needs to be said?

### CODE REVIEW

**Comment by hamishwillee** [comment]
PS I haven't yet been able to get any of these to work on Windows properly, because I can't get simulation to work except in a VM. I'll try verify via HITL.

**Comment by priseborough** [comment]
Logitech Gamepad F310 (usb connection only) works with QGC on my mac running OSX Sierra

**Comment by julianoes** [comment]
I use the old school [Logitech Extreme 3D Pro](http://gaming.logitech.com/en-ch/product/extreme-3d-pro-joystick) and it works. I map throttle on the wheel and it has "yaw" as well.

**Comment by hamishwillee** [comment]
Thanks @priseborough @julianoes Have you tried either of these on Windows? I'm trying to get ideas about https://github.com/mavlink/qgc-user-guide/pull/93#issuecomment-312802666

**Comment by julianoes** [comment]
@hamishwillee I have not I'm afraid.

**Comment by hamishwillee** [comment]
Thanks @julianoes  (and @priseborough ). 

Julian 
- have you tried on mac AND linux?
- you mapped throttle to a wheel. What did you map Yaw to?

**Comment by julianoes** [comment]
@hamishwillee I have tried Linux for sure. I can try the other two tonight.
The joystick can twist about 20 degrees in the yaw axes, so that's easy.

**Comment by julianoes** [comment]
@hamishwillee I just tried it on Mac and Windows as well. All worked flawless, really nice!

**Comment by hamishwillee** [comment]
Thanks @julianoes ! I've made an update to make the setup clear.

@DonLakeFlyer I'm merging this. I'll create a separate issue on my Windows problems.

**Comment by DonLakeFlyer** [comment]
> Does virtual thumbstick work for both Ardupilot and PX4?
> Does USB Joystick work for ArduPilot too?

Neither works for ArduPilot.

> Can you enable both virtual thumbsticks and a USB joystick?

I think you can, but that's just a fluke. Not sure what will happen.

> I have listed a few joysticks that I either tested (Taranis, PS4) or were documented in old qgroundcontrol. Do we know of any more - if so which, and any limitations known?

Joystick support comes from SDL2. Not sure if there are limitations or not as to what is supported.

> What "protocol" must a joystick follow to work. ie are joysticks sufficiently common in terms of USB protocol that we can say "any usb two-stick joystick has a good chance of working"?

Just needs to work with the normal OS.

> The PX4 param has another option "Virtual RC by Joystick" - what does this do?

Tell the firmware to no complain about no RC input.

**Comment by hamishwillee** [comment]
Thanks Don. I fixed this in https://github.com/mavlink/qgc-user-guide/pull/95 - added "(PX4)" to topics in the main sidebar menu and "(PX4 only)" to the page titles.

**Pull request merged**
