### PR TITLE
update linux instructions

### PR DESCRIPTION
**Pull request by dagar**

### CODE REVIEW

**Comment by dagar** [comment]
The latest folder on s3 always has the last release build. Do you want to use those links here, or change them manually to have control over each release?

**Comment by DonLakeFlyer** [comment]
Do you mean Stable not going right to 3.0 directory?

**Comment by dagar** [comment]
Tagged releases (stable builds) go to both `qgroundcontrol/vX.Y.Z/` and `qgroundcontrol/latest/` on s3.

**Comment by DonLakeFlyer** [comment]
Yeah can you change to just be latest then.

**Comment by dagar** [comment]
done

**Comment by DonLakeFlyer** [comment]
Thanks Daniel

**Comment by LorenzMeier** [comment]
@dagar How hard would be auto-updating the Ubuntu package?

**Comment by LorenzMeier** [comment]
Well I recant. App image is great.

**Pull request merged**
