### PR TITLE
Update radio setup 

### PR DESCRIPTION
**Pull request by hamishwillee**
This integrates content from recently updated PX4 guide. @DonLakeFlyer ,

1. I decided to include the text and images from PX4 user guide for additional setup rather than just link to those sections. Reason being that if someone comes to this from QGC they probably don't want to link off elsewhere. If you disagree let me know and I'll remove those sections and link.
2. I haven't separated additional settings into PX4/ArduPilot explicitly because the settings share the "Spektrum" setup. Instead I display the settings for both firmwares and identify which autopilot is relevant in the headings.

Let me know if this is OK.

### CODE REVIEW

**Comment by hamishwillee** [comment]
@DonLakeFlyer Can you please check this too?

**Comment by DonLakeFlyer** [comment]
Looks good. Copy Trims should be on for ArduPilot as well now.

**Comment by hamishwillee** [comment]
@DonLakeFlyer 
>  Copy Trims should be on for ArduPilot as well now.
In a QGC daily build or in the current stable build? I tried this on 3.1.3 with latest ardupilot and did not see trims.

**Comment by DonLakeFlyer** [comment]
Daily build

**Pull request merged**
