### PR TITLE
ci: gh-actions build book

### PR DESCRIPTION
**Pull request by mrpollo**
This is the partial gh-action setup, still need to figure out the gh-pages portion

### CODE REVIEW

**Comment by hamishwillee** [comment]
Thanks @mrpollo 
I don't know much about gitbook actions, so it is hard for me to assess. However some points:
1. The devguide uses this jenkinsfile currently: https://github.com/PX4/Devguide/blob/master/Jenkinsfile#L42
1. The build in the devguide is done using this docker image:  image 'px4io/px4-docs:2020-01-05'
1. The steps look right. Next step is deployment. The name of the repo apparently matters - ie it is dev.px4.io to match the URL we plan to create
1. The devguide and PX4 have code in there to build any branch with right format and publish that with a full branch URL. This may result in a different URL for QGC and MAVLink. Daniel was of the opinion that we map the PX4 pattern. I'm OK with that. Later on we can then do versions if needed.
1. Recent gotcha for me doing this manually is that Node 6 is the best version to use. Newer versions break things.
1.

**Comment by mrpollo** [comment]
1. I'm using this as an example for my work, I'll try to replicate the same logic
2. @dagar what is [px4io/px4-docs](https://hub.docker.com/repository/docker/px4io/px4-docs/general) doing? is it just for the npm environment?
3. can you create the repo, please?
4. Regarding this repository only, can you give me example URLs? what do I need to build?
5. Can you point me in the right direction? I have been using the latest node version and everything seems to work fine (so far)

**Comment by hamishwillee** [comment]
2. [px4-docs definition here](https://github.com/PX4/containers/blob/master/docker/Dockerfile_docs). It uses ubuntu bionic to get node and the client.
5. 
   > I have been using the latest node version and everything seems to work fine (so far)

   It is "touchy". Works fine here, but if you get the latest desktop version via canonical it used to work but does not now - I had to revert to nodejs 6 recently to get everything to build. So I know node 6 works but not necessarily other versions.

I assume this and the rest is for @dagar !

**Comment by hamishwillee** [comment]
I think this is working now, except for the DNS, which is still waiting on @dagar . So closing this.

**Pull request closed without merging**
