### PR TITLE
Add information about Windows shortcuts/OpenGL

### PR DESCRIPTION
**Pull request by hamishwillee**
This adds information about the three windows start menu shortcuts - as requested here: https://github.com/mavlink/qgroundcontrol/issues/6047#issuecomment-358475660

@DonLakeFlyer I wasn't sure exactly the right place to put this. In the end I decided that a note where you install QGC that links to a more detailed explanation in a troubleshooting section (which I put under "support"). If we had more troubleshooting information I'd spawn that out to another page.

### CODE REVIEW

**Comment by hamishwillee** [comment]
P.S. In https://github.com/mavlink/qgroundcontrol/issues/6047#issuecomment-358658504 there was the suggestion of a compatibility list. If we could provide a minimum spec that would be cool, but I suspect very challenging, and we're unlikely to "usefully" be able to spec what computers might have the right drivers.

**Comment by DonLakeFlyer** [comment]
@natergator Could you review this?

**Comment by hamishwillee** [comment]
@NaterGator Can you please confirm this is OK?

**Comment by hamishwillee** [comment]
No worries - thanks @NaterGator !

**Pull request merged**
