### PR TITLE
Add a note about dump1090 to the ADSB server documentation.

### PR DESCRIPTION
**Pull request by booo**
I added a line about dump1090 to the documentation. I tested the setup with dump1090 and it worked fine.

### CODE REVIEW

**Comment by hamishwillee** [comment]
@booo Thanks very much. Unfortunately I don't know much about ADS-B, and I suspect we could provide just a little more context and help people use this.

Is this setting for integrating a single ADS-B transponder for a vehicle that happens to integrate via IP network (instead of say using mavlink message like [ADSB_VEHICLE](https://mavlink.io/en/messages/common.html#ADSB_VEHICLE). Or is this for integrating with an internet service that collates a whole bunch of ADS-B traffic?

I was assuming the later - i.e. that this setting would allow QGC to get ADS-B information from the internet, and that dump1090 is one such service, but it would help if you could confirm.

Further, if it is an Internet service, do we know of other ones?

**Comment by hamishwillee** [comment]
@booo @DonLakeFlyer Can you clarify my question above?

**Comment by DonLakeFlyer** [comment]
Here: https://github.com/mavlink/qgroundcontrol/issues/9068

**Comment by hamishwillee** [comment]
@DonLakeFlyer Yes, I read that, and you'll see that at the time I commented that it doesn't help someone who doesn't already know about how it all works. 

I then read the links, and they assume you already know how it all works. 

My guess is that dumpaware is a server. You can host it somewhere and connect to it to get information about ADS-B traffic. That's where this falls apart - where is that information coming from? If you follow the rabbit hole there is something called PiAware and something called RTLSDR and a whole bunch of other possible sources. But it isn't clear whether I set up my own dumpaware thingy to connect to my own RTLSDR thingy or if dumpaware is talking to another server somewhere called flightaware. etc etc. 

Now I could read more, but I'd never be "sure", and 2 minutes of time from someone who knows this crap could save me 2 hours. Which is why I asked :-(

**Comment by DonLakeFlyer** [comment]
Sorry I pointed to the wrong thing. The key information is in the pull: https://github.com/mavlink/qgroundcontrol/pull/8046 which is only indirectly linked to what I pointed to. It's pretty simple:
* Get an RTL-SDR dongle and antenna
* Do whatever is needed to get it working on the OS you are using. That may require some drivers be installed. Internet search is your friend here. We shouldn't try to doc much past figure it out yourself.
* Get a pre-built version or build your own version of dump1090 for you OS. Once again internet search will give you the answers. We shouldn't try to doc much past figure it out yourself.
* Run `dump1090 --net`
* Run QGC
* ADSB vehicles in your area will now show up on the map

Details:
* `dump1090 --net` sends data out a TCP link on localhost port 30003. (127.0.0.1:30003)
* The data format is SBS, which is some sort of ADSB standard format.
* You can hook QGC up to any random thing local or remote which happens to output SBS format ADSB data on a TCP port as well.

**Comment by hamishwillee** [comment]
@DonLakeFlyer (and @booo ). Thanks very much. Docs updated. Are we all happy to merge?

**Comment by booo** [comment]
Looks very good. Thanks a lot for your work!

**Comment by hamishwillee** [comment]
Awesome. Thank you. MErged.

**Pull request merged**
