### PR TITLE
 added persian language

### PR DESCRIPTION
**Pull request by mohammada315**
dear Mavlink Managers
I am going to publish a persian document
Is it publishable?

### CODE REVIEW

**Comment by hamishwillee** [comment]
Thanks @mohammada315 , but no, we cannot accept this translation.

In general our translation is done via a Crowdin tool as this allows the source and translations to be kept in Sync. Information on that is here: http://docs.px4.io/main/en/contribute/translation.html

We do not support Persian as a target language for the documentation, and I wouldn't add it unless you were able to provide a "team" of people who wanted to work on that.

Where we could use translation help is in QGroundControl itself! This uses a very similar approach via crowdin.

**Comment by mohammada315** [comment]
Could you please tell me, how many people considered as a team?

**Comment by hamishwillee** [comment]
How many do you have?

I'd prefer to see commitment to documenting in the Qgroundcontrol application before enabling a new language for the documentation.

The main reason for this is that each new language adds a lot of overhead to the build time of the documentation. Unless we have committed translators groups what normally happens is that about 10% of the docs get done and then people run out of interest.

**Comment by mohammada315** [comment]
We have translated the QGC, but we can not send the source to you because of the company limitations.  But we also want to have freedom activities We want to translate the QGC documents. 
img

**Comment by hamishwillee** [comment]
OK. Please join crowdin then using this link: https://crowdin.com/project/qgroundcontrol-user-guide/invite?d=q6l6n415c5j5n463k533n493633363

Note however I won't publish until there is at least 30% coverage of the documentation, and reserve the right to not build the content if breaks our continuous integration. You would however be able to build your own copy :-)

**Comment by mohammada315** [comment]
ok , thanks hamish miller

**Pull request closed without merging**
