### PR TITLE
Updates for Stable V3.2

### PR DESCRIPTION
**Pull request by DonLakeFlyer**
Made the following changes to reflect availability of Stable 3.2:
* Move detailed daily build release note to long form release note (stable_v3.2_long.md)
* Created short form of release notes (stable_v3.2_short.md). Includes link to long form notes. I will also use this short form as releases notes to various store builds and forum announcements.
* Emptied out daily build release notes
* Release Notes link from Summary points to short form
* Add "Previous Release Notes" section to Summary for old release notes.

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
@hamishwillee I'm going to push this through and then you are welcome to reorganize as you like. Also now that 3.2 is out the detailed 3.2 notes should be merged back into mainline docs.

**Comment by hamishwillee** [comment]
Cheers. FYI I'm going to have to reorganise this. You may not be aware that content that is not in the TOC/SUMMARY.md does not get built, so some links are broken. Also before renaming files (e.g. like release_notes.md worth thinking about whether the content could reasonably be changed, keeping the links intact.

**Comment by DonLakeFlyer** [comment]
I changed from release_note.md to a version specific file so that it would be easier to move from release to release. That way I can just use the same file for previous releases, and make a new file for a new release. Probably 6 of one, half dozen of another as to whether that is really valuable time savings.

**Comment by hamishwillee** [comment]
OK, restructured in #99. It is OK to have separate files for releases but the home page should not move about because chasing links is a pain. As you'll see all "short form" release notes live in the same release notes page, and the main notes are separately referenced as sub pages.

Not sure where helping integrate these changes fits into priority list. Suggest you don't wait for me to do this if you see an easy fix.

**Comment by DonLakeFlyer** [comment]
> but the home page should not move about because chasing links is a pain.

Make sense

**Pull request merged**
