### PR TITLE
Setup: add entry for motor testing

### PR DESCRIPTION
**Pull request by Williangalvani**
This describes the Motors Setup page for Ardusub and its usage.
[See final result here](https://github.com/Williangalvani/qgc-user-guide/blob/motors/en/SetupView/Motors.md).

### CODE REVIEW

**Comment by hamishwillee** [comment]
@Williangalvani Looks good.
- Is this in a released build or daily build?
- The Frame tab is undocumented - I presume this is like the Airframe tab? Can we add something for that?
- The text in screen about blue robotics could perhaps be generalised - or is it dependent on this particular frame? By which I mean that you could say "Many thrusters are not designed to be used in air (for example, water-lubricated thrusters from BlueRobotics)
- Text about moving the slider in image "the thruster should push air/water towards the cable entering the housing". Is this text specific to the frame/will this orientation make sense for all thrusters? Specifically, this isn't easy for me to understand like "front" or "back" might be, or clockwise/anticlockwise.

I'll give it a minor subedit once it is in. @DonLakeFlyer any feedback?

**Comment by Williangalvani** [comment]
Thanks @hamishwillee 
> * Is this in a released build or daily build?

It is still in daily.
 > * The Frame tab is undocumented - I presume this is like the Airframe tab? Can we add something for that?

This is next on my list.

I'll let @jaxxzer address the next points

**Comment by jaxxzer** [comment]
> The text in screen about blue robotics could perhaps be generalised - or is it dependent on this particular frame? By which I mean that you could say "Many thrusters are not designed to be used in air (for example, water-lubricated thrusters from BlueRobotics)

It is not frame dependent. I understand your sentiment about generalizing things. The thing of it is that AFAIK, the Blue Robotics thrusters are the only thrusters on the market that will work with ArduSub. 


> Text about moving the slider in image "the thruster should push air/water towards the cable entering the housing". Is this text specific to the frame/will this orientation make sense for all thrusters? 

It applies to all of the frames supported by ArduSub, if the thrusters are mounted as the frames are drawn.

> Specifically, this isn't easy for me to understand like "front" or "back" might be, or clockwise/anticlockwise.

The thrusters look symmetrical (aside from where the cable enters the housing), and users are often confused about what is considered the 'front'. The thrusters are counter rotating, so clockwise/anticlockwise is not very helpful and would add ambiguity. I've phrased it this way to be precise, as this direction set up is the number one thing people make mistakes on in ArduSub setup.

A pull request/issue may be put in mavlink/qgroundcontrol to change the text.

**Comment by hamishwillee** [comment]
@Williangalvani Thanks very much. If this is daily build, shall we wait for the imminent release before pushing it in.

@DonLakeFlyer Do you think we might be better off adding versioned builds? I can, for example, create a doc build that has versions based on branches in the docs repo - so we could have master, stable, or master, 3.4, whatever....

What this means is that you can fully doc things as you want them when you code them, and no one using the stable release needs to worry about that. 

@jaxxzer Thanks - makes sense - if frames/thrusters vary in future we can revisit.

**Comment by DonLakeFlyer** [comment]
> Do you think we might be better off adding versioned builds?

Right now, I tend to add new feature descriptions to the daily build release page. Not sure if versioning would just be more confusing.

**Comment by hamishwillee** [comment]
>> Do you think we might be better off adding versioned builds?

> Right now, I tend to add new feature descriptions to the daily build release page. Not sure if versioning would just be more confusing.

It would be less confusing and overall less maintenance. You would still have a daily build page, but it would just be a thin link through to the actual new docs. 

To do this:
- You would have two branches - master (daily build) and stable (current release)
- Docs would go into master in the right place, and you'd just link to them from the daily build section. 
- On release you'd 
  - push master into stable docs branch and in that branch move the daily build section into a release note. The "stable" docs would be up to date if you did a good job documenting as you went along.
  - In master, clear the "daily build" page. 

Entirely up to you.

**Comment by Williangalvani** [comment]
@hamishwillee This is also in 3.5.0

**Comment by hamishwillee** [comment]
Merged then! Thanks @Williangalvani

**Pull request merged**
