### PR TITLE
Updates for new features

### PR DESCRIPTION
**Pull request by DonLakeFlyer**
Major update to daily build features. Settings and Plan are now up to date with all new features. Still need full pass through the rest. Important to document all new stuff for release.

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
@hamishwillee I'll push this through and you can take a look for any crappy wording I've used.

**Comment by hamishwillee** [comment]
@DonLakeFlyer I feel used :-) Created #75 to fix up some English - more concerned about how we integrate this info into the body of the docs when the release is made. Also created https://github.com/mavlink/qgc-dev-guide/issues/18 as we'll need to document the new .plan format and archive (?) the old doc formats.

**Comment by DonLakeFlyer** [comment]
> more concerned about how we integrate this info into the body of the docs when the release is made.

I figure it's just a matter of copy paste into appropriate places.

**Comment by hamishwillee** [comment]
>> more concerned about how we integrate this info into the body of the docs when the release is made.
> I figure it's just a matter of copy paste into appropriate places.

Probably not if done properly :-) 

How is recording change information done? So for example we have a feature X that changes things compared to previous version. We can do one of:
1. Do we have separate docs versions (I believe Gitbook supports this)
1. Do we have the one version but add a note "X has changed since previous verion"
1. Do we just document "how it is now"

**Comment by DonLakeFlyer** [comment]
I like the idea of having a separate page which lists out the detailed new stuff in daily builds. It provides the user an easy place to see everthing new in one place. I see that as being really important. Then you can keep that as version history. And the use it as the starting point for updating the docs when the stable comes out.

**Comment by hamishwillee** [comment]
@DonLakeFlyer I get that, and fully support it. The question is more about what happens after we have a new stable build. Do we have to keep track of changes with respect to the previous version? Or is it that once 3.2 is out we update the docs and forget that version 3.1 ever existed?

**Comment by DonLakeFlyer** [comment]
> Or is it that once 3.2 is out we update the docs and forget that version 3.1 ever existed?

I would say the answer to that is yes. Other than archiving the daily build new feature page somewhere since it create a nice history.

**Comment by hamishwillee** [comment]
Great. Thanks.

**Pull request merged**
