### PR TITLE
Init Korean version

### PR DESCRIPTION
**Pull request by jeyong**
Translation to Korean

### CODE REVIEW

**Comment by hamishwillee** [comment]
@DonLakeFlyer This looks pretty good to me via quick google translate test :-). Are there any particular gating factors you'd like met before integration? For me I'd minimally like the summary page (TOC) to additionally be translated.

**Comment by hamishwillee** [comment]
@jeyong Looking good! Do you want to continue adding to this PR or is it better for you to continue merging into this PR until some point. Before we merge it would be good if you could update the SUMMARY.md page so that all the sidebar items show as translated. 

I have also just moved a few files around, as you can see from https://github.com/mavlink/qgc-user-guide/pull/66. You might want to move yours around to match :-)

One other thing, right now it is easy to track changes, but in future it might become harder. In order to make this easier we have the [translation policy here](https://github.com/px4/px4_user_guide#translation). You may find it useful to add translation metadata like this to the top of your pages:
```
---
translated_page: https://github.com/PX4/Devguide/blob/master/en/setup/config_initial.md
translated_sha: 95b39d747851dd01c1fe5d36b24e59ec865e323e
translated: true
---
```

The SHA is like a timestamp for the last time the file was updated. So with this information we can write tools to tell you if any file changed since last time you did a translation. I haven't written those yet.

Regards
Hamish

**Comment by jeyong** [comment]
I think over how I handle SUMMARY.md.
Actually each topic means menu of QGC. Menus does support only English. So I decided to leave unchanged. 
But it looks odd, I'll translate to Korean.

**Comment by DonLakeFlyer** [comment]
> Are there any particular gating factors you'd like met before integration?

Your call on that.

**Comment by jeyong** [comment]
I just translated SUMMARY.md. Now it's ready to integrate.

**Comment by hamishwillee** [comment]
Not quite :-(

I tried this (created a merge of your branch into a copy of master). For some reason gitbook does not create links for the pages that were moved. So for example QuickStart/QuickStart.md does not link, and neither does download_and_install.md.

However if you move the files into the same places as the English version (e.g. getting_started/download_and_install.md) and update the Summary file then all the links do work.  Are you able to do this?

Regards
Hamish

**Comment by jeyong** [comment]
I updated Summary file and all links.

**Comment by hamishwillee** [comment]
@jeyong - this is live now. Thank you :-)

**Pull request merged**
